[workspace]
members = ["plonky2x", "plonky2x-derive"]
resolver = "2"

[profile.release]
opt-level = 3
incremental = true
#lto = "fat"
#codegen-units = 1

[profile.bench]
opt-level = 3

[patch.'https://github.com/succinctlabs/curta.git']
curta = { path = "../curta/curta" }